### ISSUE TITLE
Error when using /f commands

### ISSUE THREAD

**Issue by Mxchael** [drtshock/Factions#107]
http://pastebin.com/SeNH6irn

http://file.spurlex.com/kulk/bAqoP698 

The ally sets but it errors.

**Comment by Chris8130** [comment]
I think I'm getting this aswell (not sure, just a bunch of errors)
http://hastebin.com/nekedasafi.avrasm

**Comment by Miaourt** [comment]
Getting internal error : https://gist.github.com/Technowix/97687ca193b6ad460132

**Comment by cnr** [comment]
@Technowix that issue has been resolved in the latest build

@Spurlex, @Chris8130 This issue _may_ have been resolved in the latest build. Please try it and report back.

**Comment by Mxchael** [comment]
@eueln Can confirm this issue is still occuring.

Pastebin http://pastebin.com/THca1XJr

**Comment by Mxchael** [comment]
Its interesting to note that it doesn't seem to be every time the command is typed.
