### ISSUE TITLE
Prioritisation

### ISSUE THREAD

**Issue by denizaygundev** [drtshock/Factions#22]
For some reason unlike Factions 1.6, FactionsUUID prioritises itself over all other plugins, allowing people take items out of MobArena and even type "f home" when toggled bypassing the restrictions of not being able to do "/f home" in enemy or neutral land.

**Comment by TheKnight787** [comment]
The issue is very old. Take a look here: http://dev.bukkit.org/bukkit-plugins/paintball_pure_war/tickets/164-factions-glitch-for-free-xp/

**Comment by drtshock** [comment]
We really should just rewrite the command system to use Bukkit's command handler instead of the hacky listener.

**Comment by drtshock** [comment]
Fixed https://github.com/drtshock/Factions/commit/cd65375bd9d0200f89f53d3a85b98e461dccb06b

**Comment by TheKnight787** [comment]
Not fixed. I still have the problem with players getting out of Paintball with /f home.

**Comment by drtshock** [comment]
Are they using chat to execute commands? Factions allows you to just say "f home" instead of typing "/f home" if you have the option enabled.

**Comment by TheKnight787** [comment]
I don't have the option enabled. The players bug out the paintball by just writing /pb join and after that /f home.
