### ISSUE TITLE
dun work

### ISSUE THREAD

**Issue by natemort** [drtshock/Factions#223]
work done?

**Comment by drtshock** [comment]
Fixed.

**Comment by squidicuzz** [comment]
@evilmidget38 did it work?

**Comment by natemort** [comment]
Not sure.  I reloaded my server a couple times after running buildtools, but it's still showing up red in the plugins list.  Something about "Could not pass event to Essentials" is showing up in the logs.

**Comment by squidicuzz** [comment]
Must be an issue with the config.  Probably operator error.
