### ISSUE TITLE
Factions UUID not compatible with ScoreboardStats

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#298]
Hello,

Factions UUID's config (version 1.6.9.5-U0.1.14): http://pastebin.com/GLRBjbQu
ScoreboardStats's config (version 0.8.5): http://pastebin.com/W9siHWB0

Bug: With Factions UUD, the scoreboard's SoreboardStats is show only after 2 /scoreboardstats command. Why? How fix this bug?

More informations in comments (reply to Blabla72):
http://dev.bukkit.org/bukkit-plugins/scoreboardstats/#c2434
http://dev.bukkit.org/bukkit-plugins/scoreboardstats/#c2439
http://dev.bukkit.org/bukkit-plugins/scoreboardstats/#c2444

Can you fix this problem?

Thanks,
Yoann166

**Comment by TuxCoding** [comment]
Same config:

Although it's disabled it still sets the scoreboard objective on the sidebar. 

> DISPLAY: 20c4113289c802_0
> SLOT: SIDEBAR
> NAME: 20c4113289c802_0

If you manually turned it off, ScoreboardStats can show up, because no objective is showing on the sidebar:

> DISPLAY: 20c4113289c802_0
> SLOT: null
> NAME: 20c4113289c802_0

EDIT: BTW it's a fresh installation

**Comment by drtshock** [comment]
Looks like some of the calls were outside of the config check. Should be fixed now.

**Comment by ghost** [comment]
I tried with the latest dev version (https://ci.drtshock.net/job/FactionsUUID/237/) and the problem is still there.
